// swagger/swagger.js
// const swaggerUi = require("swagger-ui-express");
// const swaggerDocument = require("../swagger-output.json"); // Import the autogenerated file

// module.exports = (app) => {
//   app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
// };






// ------------------------------------------------------------------------
// Manual Swagger Imlementation
// ------------------------------------------------------------------------

const swaggerJsDoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const swaggerOptions = {
  swaggerDefinition: {
    openapi: '3.0.0',
    info: {
      title: 'Contacts API',
      version: '1.0.0',
      description: 'API for managing contacts',
    },
    servers: [
      {
        url: process.env.NODE_ENV === "production" 
          ? "https://contacts-api-ghz7.onrender.com/api" 
          : "http://localhost:3000/api",
        description: process.env.NODE_ENV === "production" 
          ? "Production server" 
          : "Development server",
      },
    ],
  },
  apis: ['./routes/*.js'],
};

const swaggerDocs = swaggerJsDoc(swaggerOptions);

module.exports = (app) => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocs));
};
